name: Bench & Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # daily at 09:00 UTC (tweak as you like)

jobs:
  bench:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e .
      - name: Sweep A* vs RRT
        continue-on-error: true
        run: python -m scripts.evaluation.compare_planners_sweep --seeds 10 --sim-seconds 2.0

      - name: Upload report
        if: always()
  uses: actions/upload-artifact@v4
        with:
          name: planner-bench
          path: |
            artifacts/compare_planners_sweep.md
            artifacts/sweep_*.csv
            artifacts/sweep_*.json
